config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Homeland::Engine => '/homeland'
  mount Sidekiq::Web => '/sidekiq'

  draw :api
  draw :hybird

  root to: "homes#index"
  get '/58countries'=> "homes#show"

  resource :homes do
    collection do
      get :tab_books, :react_demo, :uuid, :cache_demo, :demo_page
      post :create_payment
    end
  end
  resources :sessions do
    collection do
      get :signout
      post :sign_up
    end
  end
  resources :users do
    collection do
      get :user_settings
    end
  end
  resources :books do
    member do
      get :collection, :uncollection, :settings
      put :commit_pending, :approve_pass, :approve_failure, :save_settings, :update_single_book
    end
    collection do
      get :csv_export
    end

    resources :book_chapters, path: :chapters do
      collection do
        get :get_chapter
      end
      member do
        get :big_show, :turn_js_show, :book_marks, :delete_behind
      end
    end
    resources :book_volumes, path: :volumes do
    end
  end

  resources :managements
  resources :request_logs
  resources :notifications do
    member do
      get :read
    end
  end

  namespace :user_home do
    resources :users
    # 主要的
    resources :books do
    end

    resources :authors
    resources :attachments
  end

  namespace :api do
    resource :homes do
      collection do
        get :talks
      end
    end

    resource :emoticons do
      collection do
        get :rand_show
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  enum status: [:unread, :read, :expired] # 未读 已读 失效

  enum receive_platform: {all_platform: 0, pc_platform: 1, app_platform: 2, none_platform: 3}

  enum notify_type: {
         notify_create:                   0,
         notify_transfer:                 1,
         notify_assign:                   2,
         notify_update:                   3,
         notify_remind:                   4,
       }

  enum category: [:system, :personal] #系统公告, 个人信息

  validates_presence_of :title, message:'标题不能为空!'
  validates_presence_of :body, message:'内容不能为空!'

  before_create do
    self.category ||= Notification::categories[:system]
    self.status ||= Notification::statuses[:unread]
    self.receive_platform ||= Notification::receive_platforms[:all_platform]
  end

  def as_json
    {
      id: id,
      title: title,
      body: body.to_s,
      category: category.to_s,
      status: status.to_s,
      notify_type: notify_type.to_s,
      created_at: created_at.to_s
    }
  end
end

app/controllers/api/v1/notifications_controller.rb
class Api::V1::NotificationsController < Api::V1::BaseController
  before_action :set_notification, only: [:read]
  before_action :set_default_page_params, only: [:index]

  def index
    @notifications = current_user.notifications.order(id: :desc).page(params[:page]).per_page(params[:per_page])

    render json: { code: 0, data: page_options(@notifications) }
  end

  def create
    if params[:remind_at].present?
      target_time = Time.parse(params[:remind_at]) - Time.now
    end

    @notifications = current_user.notifications.new(notification_params)
    if @notifications.save && ( target_time.nil? || target_time>0)
      if params[:remind_at].present?
        target_time = Time.parse(params[:remind_at]) - Time.now
        SendMsgToQqWorker.perform_at(target_time, @notifications.id)
      else
        SendMsgToQqWorker.perform_async(@notifications.id)
      end
      redirect_to notifications_path
    else
      if target_time<0
        flash[:danger] = "推送时间不能小于当前时间"
      else
        flash[:danger] = @notifications.errors.full_messages
      end
      render 'new'
    end

    render json: { code: 0}
  end

  def read
    @notification.status = Notification::statuses[:read]
    @notification.save

    render json: { code: 0}
  end

  private

  def set_notification
    @notification ||= current_user.notifications.find(params[:id])
  end

  def notification_params
    params.require(:notification).permit(:title, :body)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:read]
  before_action :authenticate_user!

  def index
    @notifications = current_user.notifications.order(id: :desc).page(params[:page]).per_page(params[:per_page])
  end

  def new
    @notifications = current_user.notifications.new
  end

  def create
    if params[:remind_at].present?
      target_time = Time.parse(params[:remind_at]) - Time.now
    end

    @notifications = current_user.notifications.new(notification_params)
    if @notifications.save && ( target_time.nil? || target_time>0)
      if params[:remind_at].present?
        target_time = Time.parse(params[:remind_at]) - Time.now
        SendMsgToQqWorker.perform_at(target_time, @notifications.id)
      else
        SendMsgToQqWorker.perform_async(@notifications.id)
      end
      redirect_to notifications_path
    else
      if target_time<0
        flash[:danger] = "推送时间不能小于当前时间"
      else
        flash[:danger] = @notifications.errors.full_messages
      end
      render 'new'
    end
  end

  def read
    @notification.status = Notification::statuses[:read]
    @notification.save
  end

  private

  def set_notification
    @notification ||= current_user.notifications.find(params[:id])
  end

  def notification_params
    params.require(:notification).permit(:title, :body)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<div class="container margint-20">
  <div class="row">
    <div class="col-sm-12">
      <div class="row col-sm-12">
        <table class="table table-condensed">
          <% @notifications.each do |notification|%>
              <tr>
                <td>#</td>
                <td data-id="<%= notification.id %>">
                  <% if notification.read? %>
                      <%= notification.title %>
                  <%else %>
                      <a href="<%= read_notification_path(notification) %>" data-remote="true">
                        <%= notification.title %>
                      </a>
                  <% end %>
                </td>
                <td><%= deal_string(notification.body, 50)%></td>
              </tr>
          <%end %>
          <% if @notifications.blank? %>
              <tr>
                <td colspan="2" class="align-center">暂无消息</td>
              </tr>
          <%end %>
        </table>
        <%= paginate @notifications%>
      </div>
    </div>
  </div>
</div>

app/views/notifications/new.html.erb
<div class="container">
  <h1>添加QQ信息发送</h1>
  <div>
    <%= form_for(@notifications, html:{ class: "form-horizontal"}) do |f| %>
      <div class="form-group">
        <label class="col-sm-2 control-label">标题</label>
        <div class="col-sm-10">
           <%= f.text_field :title, class:"form-control", require: true%>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">内容</label>
        <div class="col-sm-10">
           <%= f.text_area :body, class:"form-control", require: true%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">推送时间</label>
        <div class="col-sm-10">
          <%= text_field_tag :remind_at, params[:remind_at], class:"form-control datepicker"%>
        </div>
      </div>
      <%= f.submit '提交', class: "btn btn-primary float-r" %>
    <% end %>
  </div>
</div>

app/views/notifications/read.js.erb
$("td[data-id=<%= @notification.id %>]").html("<%= @notification.title %>");

var index = $("#msg_count").text();
if(index == "")
    index = 0
else{
    index = parseInt(index) - 1;
    if(index == 0){
        index = ""
    }
}

$("#msg_count").text(index);