config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Homeland::Engine => '/homeland'
  mount Sidekiq::Web => '/sidekiq'

  draw :api
  draw :hybird

  root to: "homes#index"
  get '/58countries'=> "homes#show"

  resource :homes do
    collection do
      get :tab_books, :react_demo, :uuid, :cache_demo, :demo_page
      post :create_payment
    end
  end
  resources :sessions do
    collection do
      get :signout
      post :sign_up
    end
  end
  resources :users do
    collection do
      get :user_settings
    end
  end
  resources :books do
    member do
      get :collection, :uncollection, :settings
      put :commit_pending, :approve_pass, :approve_failure, :save_settings, :update_single_book
    end
    collection do
      get :csv_export
    end

    resources :book_chapters, path: :chapters do
      collection do
        get :get_chapter
      end
      member do
        get :big_show, :turn_js_show, :book_marks, :delete_behind
      end
    end
    resources :book_volumes, path: :volumes do
    end
  end

  resources :managements
  resources :request_logs
  resources :notifications do
    member do
      get :read
    end
  end

  namespace :user_home do
    resources :users
    # 主要的
    resources :books do
    end

    resources :authors
    resources :attachments
  end

  namespace :api do
    resource :homes do
      collection do
        get :talks
      end
    end

    resource :emoticons do
      collection do
        get :rand_show
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
end

app/models/book_chapter.rb
class BookChapter < ActiveRecord::Base
  belongs_to :book, counter_cache: true
  belongs_to :book_volume, counter_cache: true

  has_many :book_marks, dependent: :destroy

  validates_presence_of :content, message:'内容不能为空!'
  validates_presence_of :title, message:'标题不能为空!'
  validates :title, uniqueness:{ scope: [:deleted_at, :book_id], message:'标题不能重复!', case_sensitive: false}
  validates_length_of :title, :maximum => 100,   :message => "标题字数不能大于20"

  # def validate
  #   # 这个方法每次保存都会调用
  #   if name.blank? && email.blank?
  #     errors.add_to_base("You mustspecify a name or an email address")
  #   end
  # end

  def next_chapter
    BookChapter.find_by(id: self.next_chapter_id)
  end

  def prev_chapter
    BookChapter.find_by(id: self.prev_chapter_id)
  end

  def as_json
    slice(:id, :title).merge({
        content: html_for_mobile(content)
    })
  end

  def html_for_mobile(content)
    "
    <html>
    <meta name='viewport' content='width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no'>
    <body style='font-size: 18px;'>#{content}</body>
    </html>
    "
  end
end

app/controllers/api/v1/book_chapters_controller.rb
class Api::V1::BookChaptersController <  Api::V1::BaseController
  include BookChaptersHelper

  skip_before_action :authenticate!, only: [:index, :show]
  before_action :set_book
  before_action :set_direct_url_in_request, only: [:show]
  before_action :set_book_chapter, only: [:show, :edit, :update, :destroy, :big_show, :book_marks]
  before_action :get_volume_for_select, only: [:update]

  def new
    @book_chapter = @book.book_chapters.new
    get_volume_for_select
  end

  #TODO 已经API改造
  def show
    @font_settings = get_font_color_and_size
    save_request_logs(last_chapter_id: @book_chapter.id)

    # 使用悲观锁
    @book.with_lock do
      @book.click_count += 1
      @book.save!
    end
    next_chapter = if @book_chapter.next_chapter
      @book_chapter.next_chapter.slice(:id, :title)
    end

    prev_chapter = if @book_chapter.prev_chapter
      @book_chapter.prev_chapter.slice(:id, :title)
    end

    render_json_data({
      book: @book.as_json,
      book_chapter: @book_chapter.as_json,
      next_chapter: next_chapter || {},
      prev_chapter: prev_chapter || {}
    })
  end

  def big_show
    @prev_book_chapter = @book_chapter
    @arr = [@book_chapter]
    (1..19).each {
      if @book_chapter && @book_chapter.next_chapter
        @book_chapter = @book_chapter.next_chapter
        @arr << @book_chapter
      else
        break
      end
    }
  end

  def edit
    @book_volumes = @book.book_volumes.order(id: :desc)
    @book_volumes = @book_volumes.map{|k| [k.title, k.id]}
    @book_volumes << ['篇头语',nil]
  end

  def create
    prev_book_chapter = BookChapter.find_by(id: params_book_chapter[:prev_chapter_id])
    next_chapter = get_next_chapter_id(prev_book_chapter)
    @book_chapter = @book.book_chapters.new(params_book_chapter.merge(
      next_chapter_id: next_chapter.try(:id)
    ))
    raise_error(params_book_chapter['word_count'].to_i > 15000 , "小说字数不能大于15000")

    if @book_chapter.save
      update_prev_chapter_next_chapter prev_book_chapter
      update_next_chapter next_chapter
      book_words_count_update

      flash[:success] = '创建成功'
      redirect_to book_path(@book)
    else
      get_volume_for_select
      flash[:danger] = @book_chapter.errors.messages.map{|k,v| v.join("")}.join(", ")
      render 'new'
    end
  rescue Exception => e #如果上面的代码执行发生异常就捕获
    flash[:danger] = e.message
    get_volume_for_select
    render 'new'
  end

  def update
    prev_words = @book_chapter.word_count
    if @book_chapter.update(params_book_chapter)
      @book.words = @book.words.to_i - prev_words.to_i + @book_chapter.word_count.to_i
      @book.save
      flash[:success] = '更新成功'
      redirect_to book_book_chapter_path(@book, @book_chapter)
    else
      flash[:danger] = '更新失败'
      render 'edit'
    end
  end

  def destroy
    _prev_chapter = @book_chapter.prev_chapter
    _next_chapter = @book_chapter.next_chapter
    if @book_chapter.destroy
      _prev_chapter.update(next_chapter_id: _next_chapter.try(:id)) if _prev_chapter.present?
      _next_chapter.update(prev_chapter_id: _prev_chapter.try(:id)) if _next_chapter.present?

      flash[:success] = '删除成功'
      redirect_to book_path(@book)
    else
      flash[:danger] = '删除失败'
      render 'show'
    end
  end

  def get_chapter
    if params[:book_volume_id].present?
      set_book_volume
      @chapter = @book_volume.book_chapters.order(id: :asc).last
      if @chapter.nil?
        prev_book_volume = @book_volume.prev_volume
        if prev_book_volume.present?
          @chapter = prev_book_volume.book_chapters.last
        else
          @chapter = @book.book_chapters.where(book_volume_id: nil).order(id: :asc).last
        end
      end
    else
      @chapter = @book.book_chapters.where(book_volume_id: nil).order(id: :asc).last
    end

    render json:{ id: @chapter.try(:id), name: @chapter.try(:title).to_s }
  end

  #TODO 已经API改造
  def book_marks
    collection = BookRelation.find_by(book: @book, user: current_user, relation_type: BookRelation::COLLECTION)
    unless collection
      BookRelation.create(book: @book, user: current_user, relation_type: BookRelation::COLLECTION)
      book_count_change("collection", "+")
    end

    book_mark = @book.book_marks.find_or_create_by(user: current_user)
    book_mark.update(book_chapter: @book_chapter)

    render_json_data({})
  end

  # ===============================================================================================================
  private

  def params_book_chapter
    params_encoded params.require(:book_chapter).permit(:title, :content, :word_count, :book_volume_id, :prev_chapter_id)
  end

  def set_book_chapter
    _cache_key = "cached_book_#{@book.id}_book_chapter_#{params[:id]}"
    @book_chapter = fetch_memberchace(_cache_key, 30.minutes) do
       @book.book_chapters.find(params[:id])
    end
  end

  def set_book_volume
    @book_volume = @book.book_volumes.find(params[:book_volume_id])
  end

  def set_book
    _cache_key = "cached_book_#{params[:book_id]}"
    @book = fetch_memberchace(_cache_key, 30.minutes) do
      Book.find(params[:book_id])
    end
  end

  def get_volume_for_select
    @book_volumes = @book.book_volumes.order(id: :desc)
    if @book_volumes
      __book_chapters = @book.book_chapters.where("book_volume_id is not null").order(book_volume_id: :asc).order(id: :asc)
      @book_chapter.prev_chapter_id ||= if __book_chapters.present?
         __book_chapters.last.try(:id)
       else
         @book.book_chapters.where(book_volume_id: nil).order(id: :asc).last.try(:id)
       end
    else
      @book_chapter.prev_chapter_id = @book.book_chapters.where(book_volume_id: nil).order(id: :asc).last.try(:id)
    end
    @book_volumes = @book_volumes.map{|k| [k.title, k.id]}
    @book_volumes << ['篇头语',nil]
  end

  def filter_page(relation)
    relation = relation.page(params[:page]).per_page(params[:per_page])
    relation
  end

  # =创建章节的时候得到下一章的id
  def get_next_chapter_id(prev_book_chapter)
    if prev_book_chapter.present?
      _prev_book_chapter_next = BookChapter.find_by(id: prev_book_chapter.next_chapter_id)
      next_chapter = _prev_book_chapter_next if _prev_book_chapter_next
    elsif book_volume = @book.book_volumes.first
      _book_chapter = book_volume.book_chapters.first
      next_chapter = _book_chapter  if _book_chapter
    end
    next_chapter
  end

  # =更新上一章的下一章为当前章
  def update_prev_chapter_next_chapter prev_book_chapter
    prev_book_chapter.update(next_chapter_id: @book_chapter.id) if prev_book_chapter.present?
  end
  # =更新上一章的下一章的上一章为当前章
  def update_next_chapter _prev_book_chapter_next
    _prev_book_chapter_next.update(prev_chapter_id: @book_chapter.id) if _prev_book_chapter_next.present?
  end
  # =这个看得理解吧
  def book_words_count_update
    @book.words = @book.words.to_i + @book_chapter.word_count
    @book.save
  end

  def book_count_change(attr_name, operation)
    sql = "update books set #{attr_name}_count = collection_count #{operation} 1 where id = #{@book.id}"
    ActiveRecord::Base.connection.execute(sql)
  end
end

app/helpers/book_chapters_helper.rb
module BookChaptersHelper
  def book_words_style count
    count = count.to_i
    if count > 1000
      "#{count/1000}K"
    else
      count
    end
  end

  def get_font_color_and_size
    attrs = {}

    if current_user.present?
      attrs[:color] = current_user.settings(:chapter_font).color
      attrs[:font_size] = current_user.settings(:chapter_font).font_size
    else
      attrs[:color] = "FFFFFF"
      attrs[:font_size] = 16
    end

    attrs
  end
end

app/views/book_chapters/_chapter_content.html.erb
<div class="content">
  <div class="book-header">
    <h3 class="book-title"><%= book_chapter.title %> <%=link_to '返回普通章节', book_book_chapter_path(@book, book_chapter.id), class: 'font-14' %></h3>
  </div>
  <div class="book-main">
    <div class="col-sm-12 bg-white pad-5 book-content" style="line-height: 1.5;font-size: 16px;">
      <%=sanitize(book_chapter.content) %>
    </div>
  </div>
</div>

app/views/book_chapters/_form.html.erb
<div class="container">
  <h1><%= @book.title %>-添加章节</h1>
  <div>
    <%= form_for(@book_chapter, url: book_path, html:{ class: "form-horizontal"}) do |f| %>
      <%= hidden_field_tag :book_id, @book.id  %>
      <div class="form-group">
        <label class="col-sm-1 control-label">章节名</label>
        <div class="col-sm-11">
          <%= f.text_field :title, class:"form-control" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-1 control-label">内容</label>
          <div class="col-sm-11">
            <%= f.text_area :content,  { class: "form-control h-250" }%>
          </div>
      </div>
      <div class="form-group">
        <label class="col-sm-1 control-label">字数</label>
        <div class="col-sm-11">
          <%= f.text_field :word_count, value: @book_chapter.word_count.to_i, class: "form-control", require: true, readonly: true%>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-1 control-label">卷标</label>
        <div class="col-sm-11">
          <%= f.select :book_volume_id, @book_volumes, {}, class: "form-control", require: true%>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-1 control-label">上一章</label>
        <div class="col-sm-11">
          <%= text_field_tag :prev_chapter_name, @book_chapter.prev_chapter.try(:title), class: "form-control", readonly: true%>
          <%= f.hidden_field :prev_chapter_id, value: @book_chapter.prev_chapter.try(:id), class: "form-control", readonly: true%>
        </div>
      </div>

      <%= f.submit '提交', class: "btn btn-primary float-r" %>
    <% end %>
  </div>
</div>

<script>
    $(function(){
      $("#book_chapter_book_volume_id").on("change", function(){
        $.ajax({
            url: '/books/<%=@book.id %>/chapters/get_chapter?book_volume_id='+$(this).val(),
            dataType:'json',
            type:'get',
            success: function(data){
                $("#prev_chapter_name").val(data.name)
                $("#book_chapter_prev_chapter_id").val(data.id)
            }
        })
      })

      var editor;
      editor = KindEditor.create('#book_chapter_content', {
        "width": "100%",
        "height": 600,
        "items": ["fontname", "fontsize", "|",
          "forecolor", "hilitecolor", "bold", "italic", "underline", "removeformat", "|",
          "justifyleft", "justifycenter", "justifyright", "insertorderedlist", "insertunorderedlist", "|",
          "emoticons", "image", "link"],
        afterChange: function(){
          $("#book_chapter_word_count").val(editor.count('text'));
        }
      })

    })


</script>

app/views/book_chapters/_page.html.erb
<nav>
  <ul class="pager">
    <li>
      <%if @book_chapter.prev_chapter_id.to_i != 0 %>
        <%= link_to '上一章(↑)', (book_book_chapter_path(@book, @book_chapter.prev_chapter_id) ), 'data-no-turbolink' => true %>
      <%end %>
    </li>
    <li>
      <%= link_to '目录', book_path(@book)%>
    </li>
    <li>
      <%if @book_chapter.next_chapter_id.to_i != 0 %>
        <%= link_to '下一章(↓)', (book_book_chapter_path(@book, @book_chapter.next_chapter_id) ), 'data-no-turbolink' => true%>
      <%end %>
    </li>
  </ul>
</nav>

app/views/book_chapters/_turn_js_show.html.erb
<div id="flipbook">
  <%(0..@totle_page).each do |i|
    show_content, index = @content_arr[i*@lines...(i+1)*@lines].join("<br>"), 0 #content[index..index+200].gsub("&","<br>")
  %>
  <div style="background: #<%= params[:color] %>">
    <%=sanitize show_content %>
  </div>
  <%index = index+200 %>
<% end %>
</div>

app/views/book_chapters/big_show.html.erb
<div class="container big_show">
  <nav>
    <ul class="pager">
      <li>
        <%= link_to '上一章(↑)', big_show_book_book_chapter_path(@book, prev_chapeter_by(20, @prev_book_chapter).prev_chapter_id) if prev_chapeter_by(20, @prev_book_chapter).prev_chapter_id.to_i != 0 %>
      </li>
      <li>
        <%= link_to '目录', book_path(@book)%>
      </li>
      <li>
        <%= link_to '下一章(↓)', big_show_book_book_chapter_path(@book, @book_chapter.next_chapter_id) if @book_chapter.next_chapter_id.to_i != 0 %>
      </li>
    </ul>
  </nav>

  <% @arr.each do |book_chapter| %>
    <%= render 'chapter_content', book_chapter: book_chapter %>
  <%end %>

  <nav>
    <ul class="pager">
      <li>
        <%= link_to '上一章(↑)', big_show_book_book_chapter_path(@book,  prev_chapeter_by(20, @prev_book_chapter).prev_chapter_id) if prev_chapeter_by(20, @prev_book_chapter).prev_chapter_id.to_i != 0 %>
      </li>
      <li>
        <%= link_to '目录', book_path(@book)%>
      </li>
      <li>
        <%= link_to '下一章(↓)', big_show_book_book_chapter_path(@book, @book_chapter.next_chapter_id) if @book_chapter.next_chapter_id.to_i != 0 %>
      </li>
    </ul>
  </nav>

</div>


<script type="text/javascript">
  $(function() {
    $(window).bind('keydown', function(e){
      // listen for arrow keys
      if (e.keyCode == 38){
        location.href = '<%= big_show_book_book_chapter_path(@book, prev_chapeter_by(20, @prev_book_chapter).prev_chapter_id) if prev_chapeter_by(20, @prev_book_chapter).prev_chapter_id.to_i != 0 %>'
      }
      else if (e.keyCode==40){
        location.href = '<%= book_book_chapter_path(@book, @book_chapter.next_chapter_id) if @book_chapter.next_chapter_id.to_i != 0 %>'
      }
    })
  })
</script>

app/views/book_chapters/book_marks.js.erb
show_flash_msg("添加书签成功！", "success")

app/views/book_chapters/edit.html.erb
<%= render 'form', book_path: book_book_chapter_path(@book, @book_chapter) %>

app/views/book_chapters/new.html.erb
<%= render 'form', book_path: book_book_chapters_path %>

app/views/book_chapters/show.html.erb
<script>
  var browser={
    versions:function(){
      var u = navigator.userAgent, app = navigator.appVersion;
      return {//移动终端浏览器版本信息
        trident: u.indexOf('Trident') > -1, //IE内核
        presto: u.indexOf('Presto') > -1, //opera内核
        webKit: u.indexOf('AppleWebKit') > -1, //苹果、谷歌内核
        gecko: u.indexOf('Gecko') > -1 && u.indexOf('KHTML') == -1, //火狐内核
        mobile: !!u.match(/AppleWebKit.*Mobile.*/), //是否为移动终端
        ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), //ios终端
        android: u.indexOf('Android') > -1 ,  //android终端或者uc浏览器,
        linux: u.indexOf('Linux') > -1,
        windows: u.indexOf('Windows') > -1,
        iPhone: u.indexOf('iPhone') > -1 || u.indexOf('Mac') > -1, //是否为iPhone或者QQHD浏览器
        iPad: u.indexOf('iPad') > -1, //是否iPad
        webApp: u.indexOf('Safari') == -1 //是否web应该程序，没有头部与底部
      };
    }(),
    language:(navigator.browserLanguage || navigator.language).toLowerCase()
  }
</script>

<div class="container ">

  <!--<div style="margin-top: 15px; text-align: center;">-->
    <!--<a href="https://www.9xiu.com/spread/download?f=test226" target="_blank">-->
      <!--<img src="/demo.gif" />-->
    <!--</a>-->
  <!--</div>-->
  <div class="book-header">
    <h3 class="book-title"><%= @book_chapter.title %></h3>
  </div>

  <div class="book-operation">
    <% if have_author_authority?(@book) %>
      <%= link_to '编辑', edit_book_book_chapter_path(@book, @book_chapter), 'data-no-turbolink' => true, class: 'btn btn-sm btn-primary'%>
      <%= link_to '删除', book_book_chapter_path(@book, @book_chapter), method: :delete, 'data-no-turbolink' => true, class: 'btn btn-sm btn-primary'%>
    <% end %>

    <%= link_to '20章连读', big_show_book_book_chapter_path(@book, @book_chapter), 'data-no-turbolink' => true, class: 'btn btn-sm btn-primary'%>
    <%= link_to '添加书签', book_marks_book_book_chapter_path(@book, @book_chapter), class: 'btn btn-sm btn-primary', remote: true%>
    <% if current_user && current_user.admin? %>
        <%= link_to '删除后续',
                    delete_behind_book_book_chapter_path(@book, @book_chapter),
                    class: 'btn btn-sm btn-danger',
                    data: {
                        no_turbolink: true,
                        confirm: 'are you sure?'
                    }
        %>
    <% end %>
  </div>

  <div class="book-main big_show row">
    <h4 class="tag">上一页(快捷键:↑) 下一页(快捷键:↓) 上一章(快捷键←) 下一章(快捷键→)</h4>
    <span class="turn_message color-red float-r margint--30px"></span>
    <div id="_book_chapter_content" class="col-sm-12 bg-white pad-5 book-content"
         style="line-height: 1.5;font-size: <%= @font_settings[:font_size].to_i == 0 ? 14: @font_settings[:font_size].to_i%>px;background: <%= "##{@font_settings[:color]}" %>;">
        <%=raw @book_chapter.content %>
        <p>更多爽文-尽在<a href="http://magicbooks.cn">魔书网</a></p>
    </div>
  </div>
  <%=render 'page'  %>

  <!--<div id="money-area">-->
    <!--<p>如果觉得可以就支持一下哦~</p>-->
    <!--<span class="money-area-img">-->
      <!--<img src="/my_wechat.jpg" style="height: 155px;">-->
    <!--</span>-->
    <!--<span class="money-area-img">-->
      <!--<img src="/my_alipay.jpg" style="height: 155px;">-->
    <!--</span>-->
  <!--</div>-->

  <div>
    <h3>阅读设置</h3>
    <%= form_for(:user, url: user_settings_users_path, method: :get) do%>
      <%= hidden_field_tag :book_id,  @book.id %>
      <%= hidden_field_tag :book_chapter_id,  @book_chapter.id %>
      <div class="form-group">
        <label class="col-sm-2 control-label">选择背景颜色：</label>
        <div class="col-sm-4">
          <%= select_tag :color, options_for_select(@colors, @font_settings[:color]), class:"form-control"%>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">选择字体大小：</label>
        <div class="col-sm-4">
          <%= select_tag :font_size, options_for_select((14..30), @font_settings[:font_size]), class:"form-control"%>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-12">
          <%= submit_tag '保存设置', class: 'btn btn-sm btn-primary' %>
        </div>
      </div>
    <%end %>
  </div>
</div>
<!--
←↑→↓↖↙↗↘↕
-->
<script type="text/javascript">
  $(function() {
  <% if Rails.env.development? %>
//    document.writeln("语言版本: "+browser.language);
//    document.writeln("<br>是否为移动终端: "+ browser.versions.mobile);
//    document.writeln("<br>ios终端: "+ browser.versions.ios);
//    document.writeln("<br>android终端: "+ browser.versions.android);
//    document.writeln("<br>linux终端: "+ browser.versions.linux);
//    document.writeln("<br>windows终端: "+ browser.versions.windows);
//    document.writeln("<br>是否为iPhone: "+ browser.versions.iPhone);
//    document.writeln("<br>是否iPad: "+ browser.versions.iPad);
//    document.writeln("<br>完整信息："+navigator.userAgent);
  <% end %>


    $("h4[class=tag]").remove();

    $(window).bind('keydown', function(e){
      // listen for arrow keys
      if (e.keyCode == 37){
        location.href = '<%= book_book_chapter_path(@book, @book_chapter.prev_chapter_id) if @book_chapter.prev_chapter_id.to_i != 0 %>'
      }

      else if (e.keyCode==39){
        location.href = '<%= book_book_chapter_path(@book, @book_chapter.next_chapter_id) if @book_chapter.next_chapter_id.to_i != 0 %>'
      }
    })
  })
</script>

app/views/book_chapters/turn_js_show.js.erb
$("#_book_chapter_content").html("<%= escape_javascript(render 'turn_js_show') %>");

$(function() {
  var flipbook = $('#flipbook');
  flipbook.turn({
    autoCenter: true,
    height:450
  });

  $(window).bind('keydown', function(e){
  // listen for arrow keys
    if (e.keyCode == 37){
      if($(flipbook).turn('page') == 1){
        $(".turn_message").html("没有上一页了")
      }
      flipbook.turn('previous');
    }
    else if (e.keyCode==39){
//      if($(flipbook).turn('pages') == $(flipbook).turn('page')){
//        $(".turn_message").html("没有下一页了")
//      }
      flipbook.turn('next');
    }
  })

//  $(flipbook).bind('turning', function(event, page, obj){
//    alert('Page '+ page);
//  })

  $(flipbook).bind('turned', function (e, page, pageObj) {
    if (!$(flipbook).turn('hasPage', page + 1)) {
      $(".turn_message").html("没有下一页了")
    }else{
      $(".turn_message").html("")
    }
//    else if(page == 0 && $(this).data('done')) {
//      $(".turn_message").html("没有上一页了")
//    }
  });
})