config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Homeland::Engine => '/homeland'
  mount Sidekiq::Web => '/sidekiq'

  draw :api
  draw :hybird

  root to: "homes#index"
  get '/58countries'=> "homes#show"

  resource :homes do
    collection do
      get :tab_books, :react_demo, :uuid, :cache_demo, :demo_page
      post :create_payment
    end
  end
  resources :sessions do
    collection do
      get :signout
      post :sign_up
    end
  end
  resources :users do
    collection do
      get :user_settings
    end
  end
  resources :books do
    member do
      get :collection, :uncollection, :settings
      put :commit_pending, :approve_pass, :approve_failure, :save_settings, :update_single_book
    end
    collection do
      get :csv_export
    end

    resources :book_chapters, path: :chapters do
      collection do
        get :get_chapter
      end
      member do
        get :big_show, :turn_js_show, :book_marks, :delete_behind
      end
    end
    resources :book_volumes, path: :volumes do
    end
  end

  resources :managements
  resources :request_logs
  resources :notifications do
    member do
      get :read
    end
  end

  namespace :user_home do
    resources :users
    # 主要的
    resources :books do
    end

    resources :authors
    resources :attachments
  end

  namespace :api do
    resource :homes do
      collection do
        get :talks
      end
    end

    resource :emoticons do
      collection do
        get :rand_show
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
end

app/views/shared/_flash_area.html.erb
<%if flash.present? %>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" role="alert">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
         <%= value %>
        </div>
    <% end %>
<%end %>

<% if @lastest_chapter %>
    <div class="alert alert-info" role="alert">
      <a href="javascript:void(0)" class="close" data-dismiss="alert">&times;</a>
      您上次阅读到章节: <%= link_to @lastest_chapter.title, book_book_chapter_path(@lastest_chapter.book, @lastest_chapter) %>
    </div>
<%end %>

app/views/shared/_home_nav.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">魔书网</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%="active" if "#{controller_name}" == "homes" && action_name == "index" %>"><a href="/" data-no-turbolink="true">首页</a></li>
        <li class="<%="active" if "#{controller_path}" == "books" %>"><a href="/books" data-no-turbolink="true">魔·书库</a></li>
        <li><a href="/homeland" data-no-turbolink="true">魔·福利</a></li>
        <%if current_user%>
          <li class="<%="active" if "#{controller_path}" == "user_home/books" %>"><a href="/user_home/books">我的书架</a></li>
          <%if current_user.admin? %>
            <li class="<%="active" if "#{controller_path}" == "homes" && action_name == "react_demo" %>"><a href="/homes/react_demo" data-no-turbolink="true">吐槽区 <i id="talk_count" class="color-red"></i></a></li>
            <li class="<%="active" if "#{controller_name}" == "managements" %>"><a href="/managements">魔·管理</a></li>
            <li class="<%="active" if "#{controller_name}" == "request_logs" %>"><a href="/request_logs">魔·日志</a></li>
          <%end %>
          <li class="<%="active" if "#{controller_path}" == "notifications" %>"><a href="/notifications" data-no-turbolink="true">魔·消息 <i id="msg_count" class="color-red"><%= @notification_count unless @notification_count.to_i <= 0 %></i></a></li>
        <%end %>
      </ul>

      <%if current_user %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/user_home/users">个人主页</a></li>
                <li><a href="/user_home/books">我的书架</a></li>
                <li><a href="/user_home/authors">我是作者</a></li>
                <li><a href="/sessions/signout">退出登录</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">附加功能</li>
                <% if current_user.admin? %>
                    <li role="presentation" class="<%='active' if controller_name=='attachments' %>" ><a href="/user_home/attachments">我的文件</a></li>
                <%end %>
                <li><a href="#">待完善</a></li>
              </ul>
            </li>
      </ul>
      <%else%>
        <%= form_for(User.new,url: sessions_path, method: :post , html:{class: 'navbar-form navbar-right'} ) do |f| %>
          <div class="form-group">
            <%=text_field_tag :login, params[:login] ,class:"form-control", placeholder:"帐号", required: true%>
          </div>
          <div class="form-group">
            <%=f.password_field :password ,class:"form-control", placeholder:"密码", required: true%>
          </div>
          <button type="submit" class="btn btn-success">登录</button>
          <a href="<%= new_session_path %>" class="btn btn-success">注册</a>
          <a href="/auth/github" class="btn btn-primary">Github登陆</a>
        <%end%>
      <%end%>

    </div>
  </div>
</nav>