config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Homeland::Engine => '/homeland'
  mount Sidekiq::Web => '/sidekiq'

  draw :api
  draw :hybird

  root to: "homes#index"
  get '/58countries'=> "homes#show"

  resource :homes do
    collection do
      get :tab_books, :react_demo, :uuid, :cache_demo, :demo_page
      post :create_payment
    end
  end
  resources :sessions do
    collection do
      get :signout
      post :sign_up
    end
  end
  resources :users do
    collection do
      get :user_settings
    end
  end
  resources :books do
    member do
      get :collection, :uncollection, :settings
      put :commit_pending, :approve_pass, :approve_failure, :save_settings, :update_single_book
    end
    collection do
      get :csv_export
    end

    resources :book_chapters, path: :chapters do
      collection do
        get :get_chapter
      end
      member do
        get :big_show, :turn_js_show, :book_marks, :delete_behind
      end
    end
    resources :book_volumes, path: :volumes do
    end
  end

  resources :managements
  resources :request_logs
  resources :notifications do
    member do
      get :read
    end
  end

  namespace :user_home do
    resources :users
    # 主要的
    resources :books do
    end

    resources :authors
    resources :attachments
  end

  namespace :api do
    resource :homes do
      collection do
        get :talks
      end
    end

    resource :emoticons do
      collection do
        get :rand_show
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :admin_authority?

  def index
    @books = Book.pending_books.includes(:author, :classification)
    @books = filter_page(@books)
  end

  def create
    titles = params[:skip_titles].split(",")
    book_urls = Rails.cache.read(:book_urls) || []
    if params[:url].present? && !book_urls.include?(params[:url])
      flash.now[:success] = '成功提交'
      DownloadBookWorker.perform_async(params[:url], titles)
      book_urls << params[:url]
      Rails.cache.write(:book_urls, book_urls)
    else
      flash.now[:danger] = []
      flash.now[:danger] << 'url 不能为空' if params[:url].blank?
      flash.now[:danger] << '已经添加过该小说' if book_urls.include?(params[:url])
    end

    render 'new'
  end

  def new

  end

  def tab_books
    param! :book_type, String, required: false
    @books = Book.online_books.includes(:classification).book_type(params[:book_type]).order("click_count desc").limit(9)
  end
end

app/views/managements/index.html.erb
<div class="container">
  <h1>书籍申请列表</h1>
  <%= link_to '添加书籍', new_management_path, class: 'btn btn-primary' %>

  <div class="book_list row">
    <table class="table">
      <tr>
        <td>书籍名称</td>
        <td>操作</td>
        <% index = 1 + ((params[:page]||1).to_i-1) * (params[:per]||30).to_i %>
      </tr>
      <% if @books.blank?  %>
        <tr><td align="center" colspan="2">
          暂无书籍申请哦～
        </td></tr>
      <%end%>
      <% @books.each_with_index  do |book, i| %>
        <tr>
          <td>
            <%=link_to "#{index}.[#{ book.classification.name rescue "其他"}] #{book.title}", book_path(book) %>
            <ul class="book_info">
              <li>人气: <%= book.click_count %></li>
              <li>作者: <%= book.author.name %></li>
              <li>章节数: <%= book.book_chapters_count %></li>
              <li>字数: <%= book.words %></li>
            </ul>
          </td>
            <td>
              <%= button_tag "", name: :approve_pass, type: :button, class: 'btn btn-sm btn-info' do%>
                <%= hidden_field_tag :book_id, book.id %>
                通过申请
              <%end%>
              <%= button_tag "", name: :approve_failure, type: :button, class: 'btn btn-sm btn-info' do%>
                <%= hidden_field_tag :book_id, book.id %>
                拒绝申请
              <%end%>
            </td>
          <% index += 1 %>
        </tr>
      <% end %>
    </table>
  </div>
  <%= paginate @books %>
</div>
<script>
  $("button[name='approve_pass']").on("click", function(){
    approve(this, "approve_pass")
  })
  $("button[name='approve_failure']").on("click", function(){
    approve(this, "approve_failure")
  })

  function approve(obj, name){
    var id = $(obj).find("[name='book_id']").val();
    var _this = $(obj)
    $.ajax({
      url: "/books/"+id+"/"+name,
      type: 'put',
      dataType: 'json',
      success: function(data){
        if(data.code==0){
          alert("审核成功！");
          $(_this).parent().html("");
        }else{
          alert(data.message)
        }
      }
    })
  }
</script>

app/views/managements/new.html.erb
<div class="container">
  <h1>添加书籍</h1>
  <div>
    <%= form_tag(managements_path, class: "form-horizontal") do  %>
        <div class="form-group">
          <label class="col-sm-2 control-label">URL</label>
          <div class="col-sm-10">
            <%= text_field_tag :url, '', class:"form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label">跳过章节(输入章节名 以,隔开)</label>
          <div class="col-sm-10">
            <%= text_area_tag :skip_titles,  '',{ class: "form-control h-250" }%>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-2">
          </div>
          <%= submit_tag '提交', class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>